# Generated by Django 6.1.1 on 2026-09-19 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_showtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='showtime',
            name='hall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='showtimes', to='movies.hall'),
            preserve_default=False,
        ),
    ]
