# Generated by Django 6.1.1 on 2026-09-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_hall_showtime_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='runtime_minutes',
            field=models.PositiveIntegerField(default=120, verbose_name=120),
            preserve_default=False,
        ),
    ]
