# Generated by Django 6.1.1 on 2026-09-29 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_booking_showtimeseat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtimeseat',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showtime_seats', to='movies.booking'),
        ),
    ]
